# Generated by Django 5.0.4 on 2024-05-03 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='日付')),
                ('attendance', models.BooleanField(verbose_name='営業日')),
                ('holiday', models.CharField(blank=True, max_length=40, verbose_name='休業理由')),
                ('begin', models.TimeField(blank=True, null=True, verbose_name='勤務開始')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='勤務終了')),
                ('leave', models.TimeField(blank=True, null=True, verbose_name='休憩開始')),
                ('back', models.TimeField(blank=True, null=True, verbose_name='休憩終了')),
            ],
            options={
                'verbose_name': '営業日',
                'verbose_name_plural': '営業日',
            },
        ),
        migrations.CreateModel(
            name='StandardWorkPattern',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='曜日')),
                ('attendance', models.BooleanField(default=True, verbose_name='営業日')),
                ('begin', models.TimeField(blank=True, null=True, verbose_name='勤務開始')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='勤務終了')),
                ('leave', models.TimeField(blank=True, null=True, verbose_name='休憩開始')),
                ('back', models.TimeField(blank=True, null=True, verbose_name='休憩終了')),
            ],
            options={
                'verbose_name': '勤務パターン',
                'verbose_name_plural': '勤務パターン',
            },
        ),
        migrations.CreateModel(
            name='TimeOffPattern',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=40, verbose_name='名称')),
                ('attendance', models.BooleanField(default=True, verbose_name='勤務')),
                ('begin', models.TimeField(blank=True, null=True, verbose_name='勤務開始')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='勤務終了')),
                ('leave', models.TimeField(blank=True, null=True, verbose_name='休憩開始')),
                ('back', models.TimeField(blank=True, null=True, verbose_name='休憩終了')),
            ],
            options={
                'verbose_name': '休暇パターン',
                'verbose_name_plural': '休暇パターン',
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('username', models.CharField(max_length=150, verbose_name='ユーザー名')),
                ('display_name', models.CharField(max_length=40, verbose_name='名称')),
                ('attendance', models.BooleanField(default=True, verbose_name='勤務')),
                ('begin', models.TimeField(blank=True, null=True, verbose_name='勤務開始')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='勤務終了')),
                ('leave', models.TimeField(blank=True, null=True, verbose_name='休憩開始')),
                ('back', models.TimeField(blank=True, null=True, verbose_name='休憩終了')),
                ('accepted', models.BooleanField(verbose_name='承認')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '休暇申請',
                'verbose_name_plural': '休暇申請',
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('time', models.TimeField(verbose_name='時刻')),
                ('username', models.CharField(max_length=150, verbose_name='ユーザー名')),
                ('action', models.CharField(max_length=20, verbose_name='種別')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='経度')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='誤差')),
                ('ua', models.TextField(blank=True, max_length=400, null=True, verbose_name='ブラウザ情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '打刻記録',
                'verbose_name_plural': '打刻記録',
            },
        ),
    ]
