# Generated by Django 5.0.6 on 2024-05-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='contact',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='連絡欄'),
        ),
    ]
